<?php
declare(strict_types=1);
namespace App\Services;
use PDO;

final class OnboardingImportService
{
    private const TYPES=['CLIENTES','PETS','PRODUTOS','SERVICOS'];
    public function type(mixed$v):string{$v=strtoupper(trim(is_scalar($v)?(string)$v:''));if(!in_array($v,self::TYPES,true))throw new \RuntimeException('Tipo de importacao invalido.');return$v;}
    public function fields(string$type):array{return match($type){'CLIENTES'=>['nome'=>true,'sobrenome'=>false,'data_nascimento'=>false,'sexo'=>false,'cpf'=>false,'email'=>false,'whatsapp'=>false],'PETS'=>['nome'=>true,'especie'=>true,'raca'=>true,'porte'=>true,'data_nascimento'=>false,'tutor_cpf'=>false,'tutor_email'=>false,'tutor_whatsapp'=>false,'tutor_nome'=>true],'PRODUTOS'=>['nome'=>true,'descricao'=>false,'sku'=>false,'codigo_barras'=>false,'preco_venda'=>false],'SERVICOS'=>['nome'=>true,'descricao'=>false,'duracao_minutos'=>false,'preco'=>false],default=>throw new \RuntimeException('Tipo inválido.')};}
    public function mapping(string$type,mixed$v):array{$fields=array_keys($this->fields($type));if(!is_array($v))throw new \RuntimeException('Mapeamento inválido.');$out=[];foreach($v as$target=>$source)if(is_string($target)&&in_array($target,$fields,true)&&(is_int($source)||(is_string($source)&&ctype_digit($source)))&&(int)$source>=0&&(int)$source<=9999)$out[$target]=(int)$source;foreach($this->fields($type)as$field=>$required)if($required&&!array_key_exists($field,$out))throw new \RuntimeException('Mapeie todos os campos obrigatórios.');$duplicates=array_count_values($out);foreach($duplicates as$source=>$count)if($count>1&&!($type==='CLIENTES'&&$count===2&&($out['nome']??null)===(int)$source&&($out['sobrenome']??null)===(int)$source))throw new \RuntimeException('Uma coluna de origem não pode alimentar esses campos.');return$out;}
    public function rows(string$type,array$mapping,mixed$v):array{if(!is_array($v)||count($v)<1||count($v)>100)throw new \RuntimeException('Cada lote deve conter de 1 a 100 registros.');$out=[];$splitFullName=$type==='CLIENTES'&&isset($mapping['nome'],$mapping['sobrenome'])&&$mapping['nome']===$mapping['sobrenome'];foreach($v as$row){if(!is_array($row))throw new \RuntimeException('Linha inválida.');$mapped=[];foreach($mapping as$field=>$column)$mapped[$field]=$this->clean($row[$column]??null,500);if($splitFullName){$parts=preg_split('/\s+/u',trim($mapped['nome']),2);$mapped['nome']=(string)($parts[0]??'');$mapped['sobrenome']=(string)($parts[1]??'');}$out[]=$mapped;}return$out;}
    public function import(PDO$pdo,int$businessId,string$type,array$rows):array{$errors=[];$imported=0;$catalogs=in_array($type,['CLIENTES','PETS'],true)?$this->classificationCatalogs($pdo):[];foreach($rows as$i=>$row){$pdo->exec('SAVEPOINT import_row');try{$row=$this->validate($type,$row);if($type==='CLIENTES')$row=$this->resolveClientClassification($row,$catalogs);if($type==='PETS')$row=$this->resolvePetClassification($row,$catalogs);$this->one($pdo,$businessId,$type,$row);$pdo->exec('RELEASE SAVEPOINT import_row');$imported++;}catch(\Throwable$e){$pdo->exec('ROLLBACK TO SAVEPOINT import_row');$pdo->exec('RELEASE SAVEPOINT import_row');$errors[]=['linha'=>$i,'erro'=>$e instanceof \RuntimeException?$e->getMessage():'Registro recusado.'];}}return['importados'=>$imported,'rejeitados'=>count($errors),'erros'=>$errors];}
    private function validate(string$type,array$r):array
    {
        foreach($this->fields($type)as$field=>$_)$r[$field]=$r[$field]??'';
        $r['nome']=$this->clean($r['nome'],180);if($r['nome']==='')throw new \RuntimeException('Nome obrigatorio.');
        if(array_key_exists('cpf',$r)){$r['cpf']=$this->digits($r['cpf']);if($r['cpf']!==''&&!$this->validDocument($r['cpf'],11))throw new \RuntimeException('CPF inválido.');}
        foreach(['email','tutor_email']as$f)if(isset($r[$f])&&$r[$f]!==''&&!filter_var($r[$f],FILTER_VALIDATE_EMAIL))throw new \RuntimeException('E-mail invalido.');
        foreach(['whatsapp','tutor_whatsapp','tutor_cpf']as$f)if(isset($r[$f]))$r[$f]=$this->digits($r[$f]);if(($r['tutor_cpf']??'')!==''&&!$this->validDocument($r['tutor_cpf'],11))throw new \RuntimeException('CPF do tutor inválido.');
        foreach(['preco','preco_venda']as$f)if(isset($r[$f])&&$r[$f]!==''){$r[$f]=$this->money($r[$f]);if($r[$f]<0)throw new \RuntimeException('Preco invalido.');}
        if(isset($r['duracao_minutos'])&&$r['duracao_minutos']!==''){$r['duracao_minutos']=(int)preg_replace('/\D/','',$r['duracao_minutos']);if($r['duracao_minutos']<1)throw new \RuntimeException('Duracao invalida.');}
        if(isset($r['data_nascimento'])&&$r['data_nascimento']!=='')$r['data_nascimento']=$this->birthDate($r['data_nascimento']);return$r;
    }
    private function one(PDO$p,int$b,string$t,array$r):void{switch($t){case'CLIENTES':$this->client($p,$b,$r);break;case'PETS':$this->pet($p,$b,$r);break;case'PRODUTOS':$this->product($p,$b,$r);break;case'SERVICOS':$this->service($p,$b,$r);break;default:throw new \RuntimeException('Tipo invalido.');}}
    private function client(PDO$p,int$b,array$r):void{$p->prepare('INSERT INTO clientes(id_estabelecimento,nome,sobrenome,data_nascimento,id_sexo,cpf,email,whatsapp_com_ddd)VALUES(:b,:n,:s,:birth,:sex,:c,:e,:w)ON CONFLICT(id_estabelecimento,cpf)WHERE cpf IS NOT NULL DO UPDATE SET nome=EXCLUDED.nome,sobrenome=EXCLUDED.sobrenome,data_nascimento=COALESCE(EXCLUDED.data_nascimento,clientes.data_nascimento),id_sexo=COALESCE(EXCLUDED.id_sexo,clientes.id_sexo),email=COALESCE(EXCLUDED.email,clientes.email),whatsapp_com_ddd=COALESCE(EXCLUDED.whatsapp_com_ddd,clientes.whatsapp_com_ddd)')->execute(['b'=>$b,'n'=>$r['nome'],'s'=>$r['sobrenome']?:null,'birth'=>$r['data_nascimento']?:null,'sex'=>$r['id_sexo'],'c'=>$r['cpf']?:null,'e'=>$r['email']?:null,'w'=>$r['whatsapp']?:null]);}
    private function pet(PDO$p,int$b,array$r):void{$sql="SELECT id FROM clientes WHERE id_estabelecimento=:b AND ((:cf<>'' AND cpf=:cv)OR(:ef<>'' AND lower(email)=lower(:ev))OR(:wf<>'' AND whatsapp_com_ddd=:wv)OR(:nf<>'' AND lower(concat_ws(' ',nome,sobrenome))=lower(:nv))) ORDER BY CASE WHEN cpf=:co AND :cp<>'' THEN 0 WHEN lower(email)=lower(:eo)AND :ep<>'' THEN 1 WHEN whatsapp_com_ddd=:wo AND :wp<>'' THEN 2 ELSE 3 END,id LIMIT 2";$q=$p->prepare($sql);$q->execute(['b'=>$b,'cf'=>$r['tutor_cpf'],'cv'=>$r['tutor_cpf'],'ef'=>$r['tutor_email'],'ev'=>$r['tutor_email'],'wf'=>$r['tutor_whatsapp'],'wv'=>$r['tutor_whatsapp'],'nf'=>$r['tutor_nome'],'nv'=>$r['tutor_nome'],'co'=>$r['tutor_cpf'],'cp'=>$r['tutor_cpf'],'eo'=>$r['tutor_email'],'ep'=>$r['tutor_email'],'wo'=>$r['tutor_whatsapp'],'wp'=>$r['tutor_whatsapp']]);$ids=$q->fetchAll(PDO::FETCH_COLUMN);if(count($ids)!==1)throw new \RuntimeException(count($ids)>1?'Tutor ambíguo; use CPF, e-mail ou WhatsApp único.':'Tutor não encontrado; importe ou corrija o cliente antes.');$pet=$p->prepare('INSERT INTO pets(id_estabelecimento,nome,id_especie,id_raca,id_porte,data_nascimento)VALUES(:b,:n,:species,:breed,:size,:d) RETURNING id');$pet->execute(['b'=>$b,'n'=>$r['nome'],'species'=>$r['id_especie'],'breed'=>$r['id_raca'],'size'=>$r['id_porte'],'d'=>$r['data_nascimento']?:null]);$p->prepare('INSERT INTO pets_tutores(id_estabelecimento,id_pet,id_cliente)VALUES(:b,:pet,:client)ON CONFLICT DO NOTHING')->execute(['b'=>$b,'pet'=>$pet->fetchColumn(),'client'=>$ids[0]]);}
    private function classificationCatalogs(PDO$p):array{return['especies'=>$p->query('SELECT id,codigo,nome FROM pets_especies WHERE ativo=TRUE')->fetchAll(),'racas'=>$p->query('SELECT id,id_especie,codigo,nome FROM pets_racas WHERE ativo=TRUE')->fetchAll(),'portes'=>$p->query('SELECT id,codigo,nome FROM pets_portes WHERE ativo=TRUE')->fetchAll(),'sexos'=>$p->query('SELECT id,codigo,nome FROM clientes_sexos WHERE ativo=TRUE')->fetchAll()];}
    private function resolveClientClassification(array$r,array$catalogs):array{$r['id_sexo']=$r['sexo']===''?null:(int)$this->catalogItem($catalogs['sexos'],$r['sexo'])['id'];return$r;}
    private function resolvePetClassification(array$r,array$catalogs):array{$species=$this->catalogItem($catalogs['especies'],$r['especie']);$size=$this->catalogItem($catalogs['portes'],$r['porte']);$breeds=array_values(array_filter($catalogs['racas'],fn(array$item)=>(int)$item['id_especie']===(int)$species['id']));$breed=$this->catalogItem($breeds,$r['raca']);$r['id_especie']=(int)$species['id'];$r['id_raca']=(int)$breed['id'];$r['id_porte']=(int)$size['id'];return$r;}
    private function catalogItem(array$items,string$value):array{$needle=$this->key($value);foreach($items as$item)if($this->key((string)$item['codigo'])===$needle||$this->key((string)$item['nome'])===$needle)return$item;throw new \RuntimeException('Espécie, raça ou porte não reconhecido. Selecione uma opção do catálogo.');}
    private function key(string$v):string{$ascii=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$v);return trim(preg_replace('/[^A-Z0-9]+/','_',strtoupper(is_string($ascii)?$ascii:$v)),'_');}
    private function birthDate(string$v):string{$v=trim($v);$date=null;foreach(['!d/m/Y','!Y-m-d','!d-m-Y','!d/m/y']as$format){$candidate=\DateTimeImmutable::createFromFormat($format,$v);$errors=\DateTimeImmutable::getLastErrors();if($candidate&&($errors===false||($errors['warning_count']===0&&$errors['error_count']===0))){$date=$candidate;break;}}$today=new \DateTimeImmutable('today');if(!$date||$date>$today||$date<new \DateTimeImmutable('1900-01-01'))throw new \RuntimeException('Data de nascimento inválida. Use o formato DD/MM/AAAA.');return$date->format('Y-m-d');}
    private function product(PDO$p,int$b,array$r):void{$p->prepare('INSERT INTO catalogo_produtos(id_estabelecimento,nome,descricao,sku,codigo_barras,preco_venda)VALUES(:b,:n,:d,:s,:c,:v)ON CONFLICT(id_estabelecimento,sku)WHERE sku IS NOT NULL DO UPDATE SET nome=EXCLUDED.nome,descricao=EXCLUDED.descricao,codigo_barras=COALESCE(EXCLUDED.codigo_barras,catalogo_produtos.codigo_barras),preco_venda=EXCLUDED.preco_venda')->execute(['b'=>$b,'n'=>$r['nome'],'d'=>$r['descricao']?:null,'s'=>$r['sku']?:null,'c'=>$r['codigo_barras']?:null,'v'=>$r['preco_venda']===''?null:$r['preco_venda']]);}
    private function service(PDO$p,int$b,array$r):void{$p->prepare('INSERT INTO catalogo_servicos(id_estabelecimento,nome,descricao,duracao_minutos,preco)VALUES(:b,:n,:d,:m,:v)')->execute(['b'=>$b,'n'=>$r['nome'],'d'=>$r['descricao']?:null,'m'=>$r['duracao_minutos']===''?null:$r['duracao_minutos'],'v'=>$r['preco']===''?null:$r['preco']]);}
    private function clean(mixed$v,int$max):string{return mb_substr(preg_replace('/[\x00-\x1F\x7F]/u',' ',trim(is_scalar($v)?(string)$v:'')),0,$max);}
    private function digits(string$v):string{return preg_replace('/\D/','',$v);}private function money(string$v):float{$v=preg_replace('/[^0-9,.-]/','',$v);if(str_contains($v,',')&&str_contains($v,'.'))$v=str_replace('.','',$v);$v=str_replace(',','.',$v);return is_numeric($v)?round((float)$v,2):-1;}
    private function validDocument(string$v,int$length):bool{if(strlen($v)!==$length||preg_match('/^(\d)\1+$/',$v))return false;$base=$length===11?9:12;for($round=0;$round<2;$round++){$size=$base+$round;$sum=0;for($i=0;$i<$size;$i++){$weight=$length===11?($size+1-$i):(($size-1-$i)%8+2);$sum+=(int)$v[$i]*$weight;}$digit=$length===11?(($sum*10)%11)%10:(($sum%11)<2?0:11-($sum%11));if((int)$v[$size]!==$digit)return false;}return true;}
}
