<?php
declare(strict_types=1);

use App\Controllers\AuthController;
use App\Controllers\DashboardController;
use App\Controllers\OnboardingController;
use App\Controllers\ApiController;
use App\Controllers\StockController;
use App\Controllers\OnboardingImportController;
use App\Controllers\SettingsController;
use App\Core\Auth;
use App\Core\Database;
use App\Core\Env;
use App\Core\Router;
use App\Repositories\AuthRepository;
use App\Repositories\ProfileRepository;
use App\Repositories\ApiRepository;
use App\Repositories\PermissionRepository;
use App\Repositories\ApiClientRepository;
use App\Repositories\RateLimitRepository;
use App\Repositories\SessionRepository;
use App\Repositories\StockRepository;
use App\Repositories\OnboardingRepository;
use App\Repositories\IntegrationRepository;
use App\Repositories\OnboardingImportRepository;
use App\Repositories\SettingsRepository;
use App\Security\TenantContext;
use App\Services\ApiRateLimiter;
use App\Services\InputSanitizer;
use App\Services\JwtService;
use App\Services\SessionService;
use App\Services\KeyDerivationService;
use App\Services\ApiClientCredentialService;
use App\Services\CnpjLookupService;
use App\Services\CertificateStorageService;
use App\Services\IntegrationSecretService;
use App\Services\OnboardingImportService;

define('BASE_PATH',dirname(__DIR__));
$autoload=BASE_PATH.'/vendor/autoload.php';
if(is_file($autoload)) require $autoload; else spl_autoload_register(static function(string $class): void { $prefix='App\\'; if(str_starts_with($class,$prefix)){ $file=BASE_PATH.'/app/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php'; if(is_file($file)) require $file; }});
require BASE_PATH.'/bootstrap/helpers.php';
Env::load(BASE_PATH.'/.env');
date_default_timezone_set((string)env('APP_TIMEZONE','America/Sao_Paulo'));
ini_set('display_errors',env('APP_ENV','production')==='production'?'0':(env('APP_DEBUG',false)?'1':'0')); ini_set('log_errors','1'); error_reporting(E_ALL);
session_name((string)env('SESSION_NAME','pinepet_app')); ini_set('session.use_strict_mode','1'); ini_set('session.use_only_cookies','1'); ini_set('session.cookie_httponly','1'); ini_set('session.cookie_samesite','Strict');ini_set('session.sid_length','64');ini_set('session.sid_bits_per_character','6');ini_set('session.gc_maxlifetime',(string)max(1800,(int)env('SESSION_ABSOLUTE_TIMEOUT',43200)));
session_set_cookie_params(['lifetime'=>0,'path'=>'/','domain'=>'','secure'=>env('APP_ENV','production')==='production'||env('SESSION_SECURE',true),'httponly'=>true,'samesite'=>'Strict']);
session_start();
$database=new Database(require BASE_PATH.'/config/database.php');$keyDerivation=new KeyDerivationService();$sessionService=new SessionService(new SessionRepository($database),$keyDerivation);Auth::setSessionValidator(static fn(array$auth):bool=>$sessionService->validateCurrent($auth));
$auth=new AuthController(new AuthRepository($database),$sessionService);$dashboard=new DashboardController();$settings=new SettingsController(new SettingsRepository($database));$onboardingRepository=new OnboardingRepository($database);$onboardingImports=new OnboardingImportRepository($database);$onboarding=new OnboardingController(new ProfileRepository($database),$onboardingRepository,$onboardingImports,new CnpjLookupService(new IntegrationRepository($database),new IntegrationSecretService()),new CertificateStorageService());$importController=new OnboardingImportController($onboardingImports,$onboardingRepository,new OnboardingImportService());
$permissionRepository=new PermissionRepository($database);$input=new InputSanitizer();$clientCredentials=new ApiClientCredentialService($keyDerivation);$tenantContext=new TenantContext($permissionRepository,new ApiClientRepository($database),new JwtService(),$clientCredentials,new ApiRateLimiter(new RateLimitRepository($database),$keyDerivation),$input);
$api=new ApiController($tenantContext,new ApiRepository($database),$permissionRepository);$stock=new StockController($tenantContext,new StockRepository($database),$input);
$router=new Router(); require BASE_PATH.'/routes/web.php'; return $router;
