<?php
declare(strict_types=1);
$router->get('/',fn()=>App\Core\Response::redirect(App\Core\Auth::user()?'/dashboard':'/entrar',302));
$router->get('/entrar',[$auth,'showLogin']); $router->post('/entrar',[$auth,'login']); $router->post('/sair',[$auth,'logout']);
$router->get('/recuperar-senha',[$auth,'showRecovery']); $router->post('/recuperar-senha',[$auth,'recovery']); $router->get('/acesso-email',[$auth,'emailLogin']);
$router->get('/definir-senha',[$auth,'showActivation']); $router->post('/definir-senha',[$auth,'activate']);
$router->get('/primeiro-acesso',[$onboarding,'show']); $router->post('/primeiro-acesso',[$onboarding,'store']);
$router->get('/certificado-digital/oferta',[$onboarding,'certificateOffer']);
$router->post('/api/v1/onboarding/importacoes/preparar',[$importController,'prepare']);
$router->post('/api/v1/onboarding/importacoes/lote',[$importController,'batch']);
$router->post('/api/v1/onboarding/importacoes/concluir',[$importController,'finish']);
$router->get('/dashboard',[$dashboard,'index']);
$router->get('/painel',fn()=>App\Core\Response::redirect('/dashboard',301));
$router->get('/configuracoes',[$settings,'index']);$router->post('/configuracoes',[$settings,'save']);
$router->get('/api/v1/estabelecimentos',[$api,'establishment']);
$router->get('/api/v1/clientes',[$api,'clients']);
$router->get('/api/v1/pets',[$api,'pets']);
$router->get('/api/v1/agendas',[$api,'schedules']);
$router->get('/api/v1/atendimentos',[$api,'attendances']);
$router->get('/api/v1/vacinas',[$api,'vaccines']);
$router->get('/api/v1/usuarios',[$api,'users']);
$router->get('/api/v1/produtos',[$api,'products']);
$router->get('/api/v1/servicos',[$api,'services']);
$router->get('/api/v1/permissoes',[$api,'permissions']);
$router->get('/api/v1/permissoes/verificar',[$api,'checkPermission']);
$router->get('/api/v1/codebook',[$api,'codebook']);
$router->get('/api/v1/estoque',[$stock,'index']);
$router->post('/api/v1/estoque/movimentacoes',[$stock,'movement']);
