<?php
$saved=$data[['','identidade','vacinas','fiscal','pagamentos','horarios'][$step]??'']??[];$values=array_replace(is_array($saved)?$saved:[],$old);$v=static fn(string$key,mixed$fallback='')=>$values[$key]??$fallback;$checked=static fn(string$key,string$value='1')=>isset($values[$key])&&((string)(int)(bool)$values[$key]===$value||(string)$values[$key]===$value);
$titles=[1=>['Seu estabelecimento','Conte como você atua e identifique o estabelecimento.'],2=>['Serviços com vacinas','Informe se o estabelecimento aplicará vacinas e os dados técnicos necessários.'],3=>['Emissão de nota fiscal','Configure o certificado digital usado na futura emissão fiscal.'],4=>['Formas de pagamento','Escolha tudo o que seu estabelecimento pretende aceitar.'],5=>['Dias e horários','Defina quando seus clientes poderão encontrar o pet shop aberto.'],6=>['Importe seus dados','Traga clientes, pets, produtos e serviços sem precisar recadastrar tudo.']];
?>
<section class="onboarding-shell"><div class="onboarding-head"><div><span class="eyebrow">Configuração inicial</span><h1><?=e($titles[$step][0])?></h1><p><?=e($titles[$step][1])?></p></div><span class="step-pill">Etapa <?=e($step)?> de 6</span></div>
<div class="onboarding-progress" aria-label="Progresso"><span style="width:<?=e(round($step/6*100,2))?>%"></span></div><?php if($error):?><div class="alert" role="alert"><?=e($error)?></div><?php endif;?>
<form method="post" action="/primeiro-acesso" class="onboarding-form" enctype="multipart/form-data" data-onboarding-form><?=csrf_field()?>
<?php if($step===1):?>
<fieldset><legend>Seus dados</legend><div class="field-grid"><label class="field-wide">Qual é a sua função?<select name="role" required><?php foreach([''=>'Selecione uma opção','Proprietario'=>'Proprietário(a)','Socio'=>'Sócio(a)','Administrador'=>'Administrador(a)','Gerente'=>'Gerente','Veterinario'=>'Médico(a) veterinário(a)','Recepcionista'=>'Recepcionista / atendente','Groomer'=>'Tosador(a) / banhista','Auxiliar veterinario'=>'Auxiliar veterinário(a)','Financeiro'=>'Financeiro / administrativo','Estoque'=>'Estoque / compras','Outra funcao'=>'Outra função']as$key=>$label):?><option value="<?=e($key)?>" <?=$v('role')===$key?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></label></div></fieldset>
<fieldset><legend>O estabelecimento possui CNPJ?</legend><div class="choice-grid"><label><input type="radio" name="has_cnpj" value="1" <?=$checked('has_cnpj','1')?'checked':''?> required data-toggle="company-cnpj"><span><b>Sim, possui CNPJ</b><small>Consultaremos os dados automaticamente pelo servidor.</small></span></label><label><input type="radio" name="has_cnpj" value="0" <?=$checked('has_cnpj','0')?'checked':''?> required data-toggle="company-name"><span><b>Ainda não possui</b><small>Você poderá completar essa informação depois.</small></span></label></div><div class="conditional" data-section="company-cnpj" hidden><div class="field-grid"><label>CNPJ<input name="cnpj" value="<?=e($v('cnpj',$profile['cnpj']))?>" maxlength="18" autocapitalize="characters" data-document="cnpj"><small>Aceita o formato numérico e o novo CNPJ alfanumérico.</small></label><label>Nome do estabelecimento<input name="trade_name" value="<?=e($v('trade_name',$profile['nome_fantasia']))?>" maxlength="120"><small>Usaremos este nome se a consulta estiver indisponível.</small></label></div></div><div class="conditional" data-section="company-name" hidden><label>Nome do estabelecimento<input name="trade_name" value="<?=e($v('trade_name',$profile['nome_fantasia']))?>" maxlength="120"></label></div></fieldset>
<?php elseif($step===2):?>
<fieldset><legend>Você vai aplicar vacinas?</legend><div class="choice-grid"><label><input type="radio" name="aplica_vacinas" value="1" <?=$checked('aplica_vacinas','1')?'checked':''?> required data-toggle="technical-responsible"><span><b>Sim</b><small>Cadastre o responsável técnico.</small></span></label><label><input type="radio" name="aplica_vacinas" value="0" <?=$checked('aplica_vacinas','0')?'checked':''?> required><span><b>Não</b><small>Não pediremos os dados do responsável técnico.</small></span></label></div><div class="conditional" data-section="technical-responsible" hidden><div class="field-grid"><label class="field-wide">Nome do responsável técnico<input name="rt_name" value="<?=e($v('rt_name'))?>" maxlength="240"></label><label>CPF<input name="rt_cpf" value="<?=e($v('rt_cpf'))?>" maxlength="14" inputmode="numeric" data-document="cpf"></label><label>Conselho<select name="rt_council"><option value="CRMV">CRMV</option></select></label><label>Número do CRMV<input name="rt_number" value="<?=e($v('rt_number'))?>" maxlength="40"></label><label>UF do conselho<input name="rt_uf" value="<?=e($v('rt_uf'))?>" maxlength="2" data-uppercase></label><label>Validade <span class="optional">opcional</span><input type="date" name="rt_validity" value="<?=e($v('rt_validity'))?>"></label><label>E-mail <span class="optional">opcional</span><input type="email" name="rt_email" value="<?=e($v('rt_email'))?>" maxlength="254"></label><label>Telefone <span class="optional">opcional</span><input name="rt_phone" value="<?=e($v('rt_phone'))?>" maxlength="20" inputmode="tel"></label></div></div></fieldset>
<?php elseif($step===3):?>
<fieldset><legend>Você emitirá nota fiscal pelo PinePet?</legend><div class="choice-grid"><label><input type="radio" name="emitir_nf" value="1" <?=$checked('emitir_nf','1')?'checked':''?> required data-toggle="fiscal-options"><span><b>Sim</b><small>Vamos preparar sua configuração fiscal.</small></span></label><label><input type="radio" name="emitir_nf" value="0" <?=$checked('emitir_nf','0')?'checked':''?> required><span><b>Não neste momento</b><small>Você poderá ativar depois.</small></span></label></div><div class="conditional" data-section="fiscal-options" hidden><p class="fieldset-help">Você já possui certificado digital A1?</p><div class="choice-grid"><label><input type="radio" name="has_certificate" value="1" data-toggle="certificate-upload"><span><b>Sim, já possuo</b><small>Formatos .pfx ou .p12, até 5 MB.</small></span></label><label><input type="radio" name="has_certificate" value="0" data-toggle="certificate-offer"><span><b>Ainda não possuo</b><small>Quero conhecer a oferta de certificado.</small></span></label></div><div class="conditional" data-section="certificate-upload" hidden><div class="field-grid"><label class="field-wide">Certificado A1<input type="file" name="certificate" accept=".pfx,.p12,application/x-pkcs12"></label><label class="field-wide">Senha do certificado<input type="password" name="certificate_password" maxlength="255" autocomplete="new-password"></label></div></div><div class="conditional certificate-offer" data-section="certificate-offer" hidden><b>Vamos registrar sua solicitação.</b><p>Ao concluir, você poderá seguir para a oferta segura de certificado digital.</p><?php if($certificateOfferUrl!==''):?><a href="<?=e($certificateOfferUrl)?>" target="_blank" rel="noopener noreferrer">Ver oferta de certificado</a><?php endif;?></div></div></fieldset>
<?php elseif($step===4):?>
<fieldset><legend>Quais pagamentos você aceitará?</legend><div class="payment-grid"><?php $chosen=$v('payment_methods',[]);if(!is_array($chosen))$chosen=[];foreach($methods as$method):?><label><input type="checkbox" name="payment_methods[]" value="<?=e($method['codigo'])?>" <?=in_array($method['codigo'],$chosen,true)?'checked':''?>><span><?=e($method['nome'])?></span></label><?php endforeach;?></div></fieldset>
<?php elseif($step===5):?>
<fieldset><legend>Horário de funcionamento</legend><div class="schedule-tools"><button type="button" class="secondary-button" data-copy-weekdays>Repetir horário de segunda a sexta</button><button type="button" class="secondary-button" data-copy-all>Repetir em todos os dias</button></div><div class="schedule-list"><?php $days=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'];foreach($days as$day=>$label):?><div class="schedule-row"><strong><?=e($label)?></strong><label class="closed-check"><input type="checkbox" name="closed_<?=$day?>" value="1" data-closed-day="<?=$day?>" <?=$v('closed_'.$day,$day===0?'1':'0')==='1'?'checked':''?>><span>Fechado</span></label><label>Abre<input type="time" name="open_<?=$day?>" value="<?=e($day===0?'':$v('open_'.$day,'08:00'))?>" data-hour-day="<?=$day?>"></label><label>Fecha<input type="time" name="close_<?=$day?>" value="<?=e($day===0?'':$v('close_'.$day,'18:00'))?>" data-hour-day="<?=$day?>"></label></div><?php endforeach;?></div></fieldset>
<?php elseif($step===6):?>
<fieldset class="import-wizard" data-import-wizard data-business-id="<?=e($profile['id_estabelecimento']??'')?>" data-csrf="<?=e(App\Core\Csrf::token())?>"><legend>Importação de dados</legend><div class="import-step-indicator"><span data-import-step>1 de 4</span><strong data-import-title>Clientes</strong></div><section class="import-question" data-import-question><h2 data-import-question-title>Você deseja importar clientes?</h2><p data-import-question-help>Você pode fazer isso agora ou seguir para o próximo item.</p><div class="import-question-actions"><button type="button" class="primary-button" data-import-yes>Sim, importar</button><button type="button" class="secondary-button" data-import-skip>Não, continuar</button></div></section><section class="import-editor" data-import-editor hidden><button type="button" class="import-back" data-import-back>← Voltar</button><label class="import-drop"><span>Escolha sua planilha</span><small>CSV, TSV, XLS, XLSX, XLSM, XLSB ou ODS — até 20 MB</small><input type="file" accept=".csv,.tsv,.xls,.xlsx,.xlsm,.xlsb,.ods" data-import-file></label><div data-import-sheet hidden><div class="sheet-heading"><div><h2>Revise os dados</h2><p>Escolha o significado de cada coluna e edite qualquer célula antes de importar.</p></div><span data-row-count></span></div><div class="spreadsheet-wrap"><table class="import-sheet"><thead data-sheet-head></thead><tbody data-sheet-body></tbody></table></div><p class="sheet-note">Mostrando até 50 linhas para revisão. Todas as linhas do arquivo serão importadas.</p><div class="import-editor-actions"><button type="button" class="primary-button" data-start-import>Importar agora</button><button type="button" class="secondary-button" data-reset-import>Trocar arquivo</button></div></div></section><div class="import-result" data-import-result aria-live="polite"></div><div class="import-loading" data-import-loading hidden aria-live="assertive" aria-busy="true"><div class="loading-spinner" aria-hidden="true"></div><strong>Importando dados...</strong><span data-loading-status>Preparando o arquivo</span><progress max="100" value="0"></progress></div><input type="hidden" name="migration_choice" value="0" data-migration-choice><input type="hidden" name="completed_imports" value="[]" data-completed-imports></fieldset>
<?php endif;?>
<div class="onboarding-actions"><p>As informações são salvas ao avançar. Os campos são validados novamente no servidor.</p><button class="primary-button" type="submit"><?=$step===6?'Concluir configuração':'Continuar'?></button></div></form></section>
