BEGIN;
SET search_path TO pinepet, public;

CREATE OR REPLACE FUNCTION fn_definir_atualizado_em() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.atualizado_em:=CURRENT_TIMESTAMP; RETURN NEW; END;
$$;

CREATE TABLE IF NOT EXISTS cadastro_clientes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,
 nome varchar(120) NOT NULL,sobrenome varchar(120),cpf varchar(11),email varchar(254),whatsapp_com_ddd varchar(20),
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento,id),CHECK(cpf IS NULL OR cpf~'^[0-9]{11}$'),CHECK(email IS NULL OR position('@' IN email)>1)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_cadastro_clientes_cpf_por_estabelecimento ON cadastro_clientes(id_estabelecimento,cpf) WHERE cpf IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_cadastro_clientes_nome ON cadastro_clientes(id_estabelecimento,nome,sobrenome);
CREATE INDEX IF NOT EXISTS ix_cadastro_clientes_whatsapp ON cadastro_clientes(id_estabelecimento,whatsapp_com_ddd) WHERE whatsapp_com_ddd IS NOT NULL;

CREATE TABLE IF NOT EXISTS cadastro_enderecos_clientes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,id_cliente bigint NOT NULL,
 pais varchar(100) NOT NULL DEFAULT 'Brasil',cep varchar(12),estado varchar(100),cidade varchar(120),bairro varchar(120),logradouro varchar(180),numero varchar(30),complemento varchar(180),
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(id_estabelecimento,id_cliente) REFERENCES cadastro_clientes(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS ix_enderecos_clientes_cliente ON cadastro_enderecos_clientes(id_estabelecimento,id_cliente);

CREATE TABLE IF NOT EXISTS cadastro_pets (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,nome varchar(120) NOT NULL,data_nascimento date,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento,id)
);
CREATE INDEX IF NOT EXISTS ix_cadastro_pets_nome ON cadastro_pets(id_estabelecimento,nome);

CREATE TABLE IF NOT EXISTS cadastro_pets_tutores (
 id_estabelecimento bigint NOT NULL,id_pet bigint NOT NULL,id_cliente bigint NOT NULL,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(id_estabelecimento,id_pet,id_cliente),
 FOREIGN KEY(id_estabelecimento,id_pet) REFERENCES cadastro_pets(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 FOREIGN KEY(id_estabelecimento,id_cliente) REFERENCES cadastro_clientes(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS ix_pets_tutores_cliente ON cadastro_pets_tutores(id_estabelecimento,id_cliente);

CREATE TABLE IF NOT EXISTS cadastro_profissionais (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,
 nome varchar(120) NOT NULL,sobrenome varchar(120),nome_social varchar(120),cpf varchar(11),data_nascimento date,
 email varchar(254),telefone varchar(20),whatsapp_com_ddd varchar(20),cargo varchar(120),especialidade varchar(180),ativo boolean NOT NULL DEFAULT TRUE,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento,id),CHECK(cpf IS NULL OR cpf~'^[0-9]{11}$'),CHECK(email IS NULL OR position('@' IN email)>1)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_cadastro_profissionais_cpf_por_estabelecimento ON cadastro_profissionais(id_estabelecimento,cpf) WHERE cpf IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_cadastro_profissionais_nome ON cadastro_profissionais(id_estabelecimento,nome,sobrenome);
CREATE INDEX IF NOT EXISTS ix_cadastro_profissionais_ativo ON cadastro_profissionais(id_estabelecimento,ativo);

CREATE TABLE IF NOT EXISTS cadastro_profissionais_complementos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,id_profissional bigint NOT NULL,
 tipo_vinculo varchar(40),matricula varchar(60),conselho_classe varchar(40),numero_conselho varchar(60),uf_conselho varchar(2),validade_conselho date,
 formacao varchar(180),instituicao_formacao varchar(180),data_admissao date,data_desligamento date,carga_horaria_semanal numeric(6,2),observacoes text,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento,id_profissional),
 FOREIGN KEY(id_estabelecimento,id_profissional) REFERENCES cadastro_profissionais(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CHECK(uf_conselho IS NULL OR uf_conselho~'^[A-Z]{2}$'),CHECK(data_desligamento IS NULL OR data_admissao IS NULL OR data_desligamento>=data_admissao),
 CHECK(carga_horaria_semanal IS NULL OR carga_horaria_semanal>=0)
);

CREATE TABLE IF NOT EXISTS atendimento_fluxos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,nome varchar(120) NOT NULL,descricao text,
 etapas jsonb NOT NULL DEFAULT '[]'::jsonb,ativo boolean NOT NULL DEFAULT TRUE,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento,id),CHECK(jsonb_typeof(etapas)='array')
);
CREATE INDEX IF NOT EXISTS ix_atendimento_fluxos_ativo ON atendimento_fluxos(id_estabelecimento,ativo);

CREATE TABLE IF NOT EXISTS atendimento_fluxos_preferencias (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,id_fluxo_padrao bigint,
 avancar_automaticamente boolean NOT NULL DEFAULT FALSE,permitir_pular_etapas boolean NOT NULL DEFAULT FALSE,notificar_cliente boolean NOT NULL DEFAULT FALSE,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento),FOREIGN KEY(id_estabelecimento,id_fluxo_padrao) REFERENCES atendimento_fluxos(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS agenda_agendamentos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,id_cliente bigint,id_profissional bigint,
 cliente_novo boolean NOT NULL DEFAULT FALSE,cliente_novo_nome varchar(240),cliente_novo_whatsapp_com_ddd varchar(20),
 pagamento_sinal boolean NOT NULL DEFAULT FALSE,valor_sinal numeric(12,2),data_hora_inicio timestamptz NOT NULL,data_hora_fim timestamptz,status varchar(40) NOT NULL DEFAULT 'PENDENTE',
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento,id),FOREIGN KEY(id_estabelecimento,id_cliente) REFERENCES cadastro_clientes(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 FOREIGN KEY(id_estabelecimento,id_profissional) REFERENCES cadastro_profissionais(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CHECK(id_cliente IS NOT NULL OR(cliente_novo=TRUE AND cliente_novo_nome IS NOT NULL AND btrim(cliente_novo_nome)<>'')),
 CHECK(valor_sinal IS NULL OR valor_sinal>=0),CHECK(data_hora_fim IS NULL OR data_hora_fim>data_hora_inicio),
 CHECK(status IN('PENDENTE','CONFIRMADO','CANCELADO','CONCLUIDO','NAO_COMPARECEU'))
);
CREATE INDEX IF NOT EXISTS ix_agenda_agendamentos_data ON agenda_agendamentos(id_estabelecimento,data_hora_inicio);
CREATE INDEX IF NOT EXISTS ix_agenda_agendamentos_status ON agenda_agendamentos(id_estabelecimento,status,data_hora_inicio);
CREATE INDEX IF NOT EXISTS ix_agenda_agendamentos_cliente ON agenda_agendamentos(id_estabelecimento,id_cliente) WHERE id_cliente IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_agenda_agendamentos_profissional ON agenda_agendamentos(id_estabelecimento,id_profissional,data_hora_inicio) WHERE id_profissional IS NOT NULL;

CREATE TABLE IF NOT EXISTS atendimento_atendimentos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,id_cliente bigint NOT NULL,id_servico bigint NOT NULL,id_agenda bigint,
 titulo varchar(180),id_profissional bigint,id_fluxo_atendimento bigint,status varchar(50) NOT NULL DEFAULT 'PENDENTE',
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento,id),FOREIGN KEY(id_estabelecimento,id_cliente) REFERENCES cadastro_clientes(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 FOREIGN KEY(id_estabelecimento,id_agenda) REFERENCES agenda_agendamentos(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 FOREIGN KEY(id_estabelecimento,id_profissional) REFERENCES cadastro_profissionais(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 FOREIGN KEY(id_estabelecimento,id_fluxo_atendimento) REFERENCES atendimento_fluxos(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS ix_atendimento_atendimentos_cliente ON atendimento_atendimentos(id_estabelecimento,id_cliente);
CREATE INDEX IF NOT EXISTS ix_atendimento_atendimentos_agenda ON atendimento_atendimentos(id_estabelecimento,id_agenda) WHERE id_agenda IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_atendimento_atendimentos_profissional ON atendimento_atendimentos(id_estabelecimento,id_profissional) WHERE id_profissional IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_atendimento_atendimentos_status ON atendimento_atendimentos(id_estabelecimento,status);

DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['cadastro_clientes','cadastro_enderecos_clientes','cadastro_pets','cadastro_pets_tutores','cadastro_profissionais','cadastro_profissionais_complementos','atendimento_fluxos','atendimento_fluxos_preferencias','agenda_agendamentos','atendimento_atendimentos'] LOOP
  EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I','trg_'||t||'_atualizado_em',t);
  EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION fn_definir_atualizado_em()','trg_'||t||'_atualizado_em',t);
 END LOOP;
END $$;

INSERT INTO sistema_schema_versions(version,description,checksum_sha256)
VALUES('app-002-operational-base','Clientes, pets, profissionais, agenda e atendimento',NULL)
ON CONFLICT(version) DO NOTHING;
COMMIT;
