BEGIN;
SET search_path TO pinepet,public;

CREATE TABLE IF NOT EXISTS sistema_usuarios_permissoes(
 id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 id_usuario bigint NOT NULL REFERENCES acesso_usuarios(id) ON DELETE CASCADE,
 id_estabelecimento bigint NOT NULL REFERENCES organizacao_estabelecimentos(id) ON DELETE CASCADE,
 recurso varchar(60) NOT NULL,acao varchar(30) NOT NULL,permitido boolean NOT NULL DEFAULT FALSE,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_usuario,id_estabelecimento,recurso,acao),CHECK(recurso~'^[a-z][a-z0-9_]*$'),CHECK(acao~'^[a-z][a-z0-9_]*$')
);
CREATE INDEX IF NOT EXISTS ix_usuarios_permissoes_consulta ON sistema_usuarios_permissoes(id_usuario,id_estabelecimento,recurso,acao) WHERE permitido=TRUE;

CREATE TABLE IF NOT EXISTS saude_vacinas(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,id_pet bigint NOT NULL,id_profissional bigint,
 nome_vacina varchar(160) NOT NULL,fabricante varchar(120),lote varchar(80),dose varchar(60),aplicada_em date,proxima_dose_em date,
 status varchar(30) NOT NULL DEFAULT 'PENDENTE',observacoes text,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento,id),
 FOREIGN KEY(id_estabelecimento,id_pet) REFERENCES pets(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 FOREIGN KEY(id_estabelecimento,id_profissional) REFERENCES equipe_profissionais(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CHECK(status IN('PENDENTE','APLICADA','ATRASADA','CANCELADA')),CHECK(proxima_dose_em IS NULL OR aplicada_em IS NULL OR proxima_dose_em>=aplicada_em)
);
CREATE INDEX IF NOT EXISTS ix_pets_vacinas_pet ON saude_vacinas(id_estabelecimento,id_pet,aplicada_em DESC);
CREATE INDEX IF NOT EXISTS ix_pets_vacinas_proxima ON saude_vacinas(id_estabelecimento,proxima_dose_em) WHERE status IN('PENDENTE','ATRASADA');

CREATE TABLE IF NOT EXISTS catalogo_produtos(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,nome varchar(180) NOT NULL,descricao text,
 sku varchar(80),codigo_barras varchar(80),preco_venda numeric(12,2),ativo boolean NOT NULL DEFAULT TRUE,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento,id),CHECK(preco_venda IS NULL OR preco_venda>=0)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_catalogo_produtos_sku ON catalogo_produtos(id_estabelecimento,sku) WHERE sku IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_catalogo_produtos_codigo_barras ON catalogo_produtos(id_estabelecimento,codigo_barras) WHERE codigo_barras IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_catalogo_produtos_nome ON catalogo_produtos(id_estabelecimento,nome);

CREATE TABLE IF NOT EXISTS catalogo_servicos(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,nome varchar(180) NOT NULL,descricao text,
 duracao_minutos integer,preco numeric(12,2),ativo boolean NOT NULL DEFAULT TRUE,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento,id),CHECK(duracao_minutos IS NULL OR duracao_minutos>0),CHECK(preco IS NULL OR preco>=0)
);
CREATE INDEX IF NOT EXISTS ix_catalogo_servicos_nome ON catalogo_servicos(id_estabelecimento,nome);

DO $$ DECLARE t text;BEGIN
 FOREACH t IN ARRAY ARRAY['sistema_usuarios_permissoes','saude_vacinas','catalogo_produtos','catalogo_servicos'] LOOP
  EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I','trg_'||t||'_atualizado_em',t);
  EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION fn_definir_atualizado_em()','trg_'||t||'_atualizado_em',t);
 END LOOP;
END $$;

INSERT INTO sistema_usuarios_permissoes(id_usuario,id_estabelecimento,recurso,acao,permitido)
SELECT u.id,u.id_estabelecimento,p.recurso,'read',TRUE
FROM acesso_usuarios u
CROSS JOIN(VALUES('establishments'),('clients'),('pets'),('schedules'),('attendances'),('vaccines'),('users'),('products'),('services'),('permissions'),('codebook'))p(recurso)
WHERE u.id_estabelecimento IS NOT NULL AND u.status='ativo' AND u.deleted_at IS NULL
ON CONFLICT(id_usuario,id_estabelecimento,recurso,acao)DO NOTHING;

INSERT INTO sistema_schema_versions(version,description,checksum_sha256)
VALUES('app-003-api-permissions-catalogs','Permissões API, vacinas, produtos e serviços',NULL)
ON CONFLICT(version)DO NOTHING;
COMMIT;
