BEGIN;
SET search_path TO pinepet,public;

CREATE TABLE IF NOT EXISTS sistema_sessoes(
 id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,session_hash char(64) NOT NULL UNIQUE,
 id_usuario bigint NOT NULL REFERENCES acesso_usuarios(id) ON DELETE CASCADE,
 id_estabelecimento bigint NOT NULL REFERENCES organizacao_estabelecimentos(id) ON DELETE CASCADE,
 credential_binding_hash char(64) NOT NULL,user_agent_hash char(64) NOT NULL,ip_hash char(64) NOT NULL,
 emitida_em timestamptz NOT NULL,ultima_atividade_em timestamptz NOT NULL,
 expira_inatividade_em timestamptz NOT NULL,expira_absoluta_em timestamptz NOT NULL,revogada_em timestamptz,
 CHECK(expira_absoluta_em>emitida_em),CHECK(expira_inatividade_em<=expira_absoluta_em)
);
CREATE INDEX IF NOT EXISTS ix_sessoes_validacao ON sistema_sessoes(session_hash,id_usuario,id_estabelecimento) WHERE revogada_em IS NULL;
CREATE INDEX IF NOT EXISTS ix_sessoes_expiracao ON sistema_sessoes(expira_absoluta_em);

CREATE TABLE IF NOT EXISTS sistema_api_clientes(
 id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,client_id varchar(100) NOT NULL UNIQUE,
 id_estabelecimento bigint NOT NULL REFERENCES organizacao_estabelecimentos(id) ON DELETE CASCADE,
 nome varchar(160) NOT NULL,scopes text[] NOT NULL DEFAULT '{}',ativo boolean NOT NULL DEFAULT TRUE,
 segredo_verificador varchar(255),chave_assinatura_cifrada text,segredo_versao integer NOT NULL DEFAULT 0,
 expira_em timestamptz,criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK(client_id~'^[A-Za-z0-9._-]{3,100}$'),CHECK(array_position(scopes,NULL) IS NULL),CHECK(segredo_versao>=0)
);
ALTER TABLE sistema_sessoes ADD COLUMN IF NOT EXISTS credential_binding_hash char(64);
UPDATE sistema_sessoes SET credential_binding_hash=repeat('0',64),revogada_em=COALESCE(revogada_em,NOW()) WHERE credential_binding_hash IS NULL;
ALTER TABLE sistema_sessoes ALTER COLUMN credential_binding_hash SET NOT NULL;
ALTER TABLE sistema_api_clientes ADD COLUMN IF NOT EXISTS segredo_verificador varchar(255);
ALTER TABLE sistema_api_clientes ADD COLUMN IF NOT EXISTS chave_assinatura_cifrada text;
ALTER TABLE sistema_api_clientes ADD COLUMN IF NOT EXISTS segredo_versao integer NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS ix_api_clientes_tenant ON sistema_api_clientes(id_estabelecimento,ativo);

CREATE TABLE IF NOT EXISTS sistema_api_rate_limits(
 chave_hash char(64) NOT NULL,inicio_janela timestamptz NOT NULL,contador integer NOT NULL DEFAULT 1,expira_em timestamptz NOT NULL,
 PRIMARY KEY(chave_hash,inicio_janela),CHECK(contador>0)
);
CREATE INDEX IF NOT EXISTS ix_api_rate_limits_expiracao ON sistema_api_rate_limits(expira_em);

CREATE TABLE IF NOT EXISTS estoque_itens(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,id_produto bigint NOT NULL,
 quantidade_atual numeric(15,3) NOT NULL DEFAULT 0,quantidade_reservada numeric(15,3) NOT NULL DEFAULT 0,
 estoque_minimo numeric(15,3) NOT NULL DEFAULT 0,versao bigint NOT NULL DEFAULT 1,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento,id),UNIQUE(id_estabelecimento,id_produto),
 FOREIGN KEY(id_estabelecimento,id_produto) REFERENCES catalogo_produtos(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CHECK(quantidade_atual>=0),CHECK(quantidade_reservada>=0),CHECK(quantidade_reservada<=quantidade_atual),CHECK(estoque_minimo>=0),CHECK(versao>0)
);
CREATE INDEX IF NOT EXISTS ix_estoque_itens_produto ON estoque_itens(id_estabelecimento,id_produto);

CREATE TABLE IF NOT EXISTS estoque_movimentacoes(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_estabelecimento bigint NOT NULL,id_item bigint NOT NULL,
 tipo varchar(20) NOT NULL,quantidade numeric(15,3) NOT NULL,
 quantidade_anterior numeric(15,3) NOT NULL,quantidade_posterior numeric(15,3) NOT NULL,
 reservada_anterior numeric(15,3) NOT NULL,reservada_posterior numeric(15,3) NOT NULL,
 idempotency_key varchar(128) NOT NULL,id_usuario bigint REFERENCES acesso_usuarios(id) ON DELETE RESTRICT,
 id_api_cliente varchar(100),criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_estabelecimento,idempotency_key),
 FOREIGN KEY(id_estabelecimento,id_item) REFERENCES estoque_itens(id_estabelecimento,id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 FOREIGN KEY(id_api_cliente) REFERENCES sistema_api_clientes(client_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CHECK(tipo IN('ENTRADA','SAIDA','AJUSTE','RESERVA','LIBERACAO')),CHECK(quantidade>=0),
 CHECK(quantidade_anterior>=0),CHECK(quantidade_posterior>=0),CHECK(reservada_anterior>=0),CHECK(reservada_posterior>=0),
 CHECK((id_usuario IS NOT NULL)::integer+(id_api_cliente IS NOT NULL)::integer=1)
);
CREATE INDEX IF NOT EXISTS ix_estoque_movimentacoes_item ON estoque_movimentacoes(id_estabelecimento,id_item,criado_em DESC);

CREATE OR REPLACE FUNCTION fn_criar_estoque_produto()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 INSERT INTO estoque_itens(id_estabelecimento,id_produto) VALUES(NEW.id_estabelecimento,NEW.id)
 ON CONFLICT(id_estabelecimento,id_produto)DO NOTHING;
 RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_catalogo_produtos_criar_estoque ON catalogo_produtos;
CREATE TRIGGER trg_catalogo_produtos_criar_estoque AFTER INSERT ON catalogo_produtos FOR EACH ROW EXECUTE FUNCTION fn_criar_estoque_produto();

DROP TRIGGER IF EXISTS trg_sistema_api_clientes_atualizado_em ON sistema_api_clientes;
CREATE TRIGGER trg_sistema_api_clientes_atualizado_em BEFORE UPDATE ON sistema_api_clientes FOR EACH ROW EXECUTE FUNCTION fn_definir_atualizado_em();
DROP TRIGGER IF EXISTS trg_estoque_itens_atualizado_em ON estoque_itens;
CREATE TRIGGER trg_estoque_itens_atualizado_em BEFORE UPDATE ON estoque_itens FOR EACH ROW EXECUTE FUNCTION fn_definir_atualizado_em();

INSERT INTO sistema_usuarios_permissoes(id_usuario,id_estabelecimento,recurso,acao,permitido)
SELECT u.id,u.id_estabelecimento,'stock',a.acao,TRUE FROM acesso_usuarios u CROSS JOIN(VALUES('read'),('write'))a(acao)
WHERE u.id_estabelecimento IS NOT NULL AND u.status='ativo' AND u.deleted_at IS NULL
ON CONFLICT(id_usuario,id_estabelecimento,recurso,acao)DO NOTHING;

INSERT INTO estoque_itens(id_estabelecimento,id_produto)
SELECT id_estabelecimento,id FROM catalogo_produtos ON CONFLICT(id_estabelecimento,id_produto)DO NOTHING;

INSERT INTO sistema_schema_versions(version,description,checksum_sha256)
VALUES('app-004-security-sessions-stock','Sessoes persistentes, clientes JWT, rate limit e estoque idempotente',NULL)
ON CONFLICT(version)DO NOTHING;
COMMIT;
