BEGIN;
SET search_path TO pinepet,public;

CREATE TABLE IF NOT EXISTS pets_especies(
 id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 codigo varchar(40) NOT NULL UNIQUE,nome varchar(80) NOT NULL UNIQUE,ordem smallint NOT NULL DEFAULT 0,ativo boolean NOT NULL DEFAULT TRUE,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK(codigo~'^[A-Z][A-Z0-9_]{1,39}$'),CHECK(ordem>=0)
);

CREATE TABLE IF NOT EXISTS pets_portes(
 id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 codigo varchar(30) NOT NULL UNIQUE,nome varchar(60) NOT NULL UNIQUE,ordem smallint NOT NULL DEFAULT 0,ativo boolean NOT NULL DEFAULT TRUE,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK(codigo~'^[A-Z][A-Z0-9_]{1,29}$'),CHECK(ordem>=0)
);

CREATE TABLE IF NOT EXISTS pets_racas(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_especie smallint NOT NULL,
 codigo varchar(80) NOT NULL,nome varchar(120) NOT NULL,ordem smallint NOT NULL DEFAULT 0,ativo boolean NOT NULL DEFAULT TRUE,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(id_especie,id),UNIQUE(id_especie,codigo),UNIQUE(id_especie,nome),
 FOREIGN KEY(id_especie) REFERENCES pets_especies(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 CHECK(codigo~'^[A-Z][A-Z0-9_]{1,79}$'),CHECK(ordem>=0)
);

INSERT INTO pets_especies(codigo,nome,ordem)VALUES
 ('CAO','Cão',10),('GATO','Gato',20),('AVE','Ave',30),('COELHO','Coelho',40),('ROEDOR','Roedor',50),('REPTIL','Réptil',60),('OUTRA','Outra espécie',99)
ON CONFLICT(codigo)DO UPDATE SET nome=EXCLUDED.nome,ordem=EXCLUDED.ordem,ativo=TRUE;

INSERT INTO pets_portes(codigo,nome,ordem)VALUES
 ('MINI','Mini',10),('PEQUENO','Pequeno',20),('MEDIO','Médio',30),('GRANDE','Grande',40),('GIGANTE','Gigante',50),('NAO_INFORMADO','Não informado',99)
ON CONFLICT(codigo)DO UPDATE SET nome=EXCLUDED.nome,ordem=EXCLUDED.ordem,ativo=TRUE;

WITH breeds(especie,codigo,nome,ordem)AS(VALUES
 ('CAO','SRD','Sem raça definida',1),('CAO','SHIH_TZU','Shih-tzu',10),('CAO','YORKSHIRE_TERRIER','Yorkshire terrier',20),('CAO','MALTES','Maltês',30),('CAO','PUG','Pug',40),('CAO','BULLDOG_FRANCES','Buldogue francês',50),('CAO','GOLDEN_RETRIEVER','Golden retriever',60),('CAO','LABRADOR_RETRIEVER','Labrador retriever',70),('CAO','PASTOR_ALEMAO','Pastor-alemão',80),('CAO','ROTTWEILER','Rottweiler',90),('CAO','DACHSHUND','Dachshund',100),('CAO','PINSCHER','Pinscher',110),('CAO','POODLE','Poodle',120),('CAO','OUTRA','Outra raça',999),
 ('GATO','SRD','Sem raça definida',1),('GATO','SIAMES','Siamês',10),('GATO','PERSA','Persa',20),('GATO','MAINE_COON','Maine coon',30),('GATO','RAGDOLL','Ragdoll',40),('GATO','BENGAL','Bengal',50),('GATO','ANGORA','Angorá',60),('GATO','SPHYNX','Sphynx',70),('GATO','OUTRA','Outra raça',999),
 ('AVE','NAO_INFORMADA','Não informada',1),('COELHO','NAO_INFORMADA','Não informada',1),('ROEDOR','NAO_INFORMADA','Não informada',1),('REPTIL','NAO_INFORMADA','Não informada',1),('OUTRA','NAO_INFORMADA','Não informada',1)
)
INSERT INTO pets_racas(id_especie,codigo,nome,ordem)
SELECT e.id,b.codigo,b.nome,b.ordem FROM breeds b JOIN pets_especies e ON e.codigo=b.especie
ON CONFLICT(id_especie,codigo)DO UPDATE SET nome=EXCLUDED.nome,ordem=EXCLUDED.ordem,ativo=TRUE;

ALTER TABLE pets ADD COLUMN IF NOT EXISTS id_especie smallint;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS id_raca bigint;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS id_porte smallint;
UPDATE pets p SET id_especie=e.id FROM pets_especies e WHERE p.id_especie IS NULL AND e.codigo='OUTRA';
UPDATE pets p SET id_raca=r.id FROM pets_racas r JOIN pets_especies e ON e.id=r.id_especie WHERE p.id_raca IS NULL AND p.id_especie=e.id AND e.codigo='OUTRA' AND r.codigo='NAO_INFORMADA';
UPDATE pets p SET id_porte=po.id FROM pets_portes po WHERE p.id_porte IS NULL AND po.codigo='NAO_INFORMADO';
ALTER TABLE pets ALTER COLUMN id_especie SET NOT NULL;
ALTER TABLE pets ALTER COLUMN id_raca SET NOT NULL;
ALTER TABLE pets ALTER COLUMN id_porte SET NOT NULL;
DO $$BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='fk_pets_especie')THEN ALTER TABLE pets ADD CONSTRAINT fk_pets_especie FOREIGN KEY(id_especie)REFERENCES pets_especies(id)ON UPDATE RESTRICT ON DELETE RESTRICT;END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='fk_pets_raca')THEN ALTER TABLE pets ADD CONSTRAINT fk_pets_raca FOREIGN KEY(id_especie,id_raca)REFERENCES pets_racas(id_especie,id)ON UPDATE RESTRICT ON DELETE RESTRICT;END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='fk_pets_porte')THEN ALTER TABLE pets ADD CONSTRAINT fk_pets_porte FOREIGN KEY(id_porte)REFERENCES pets_portes(id)ON UPDATE RESTRICT ON DELETE RESTRICT;END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='ck_pets_raca_especie')THEN ALTER TABLE pets ADD CONSTRAINT ck_pets_raca_especie CHECK(id_raca IS NULL OR id_especie IS NOT NULL)NOT VALID;END IF;
END$$;
CREATE INDEX IF NOT EXISTS ix_pets_classificacao ON pets(id_estabelecimento,id_especie,id_raca,id_porte);
CREATE INDEX IF NOT EXISTS ix_pets_racas_especie ON pets_racas(id_especie,ativo,ordem,nome);

DROP TRIGGER IF EXISTS trg_pets_especies_atualizado_em ON pets_especies;
CREATE TRIGGER trg_pets_especies_atualizado_em BEFORE UPDATE ON pets_especies FOR EACH ROW EXECUTE FUNCTION fn_definir_atualizado_em();
DROP TRIGGER IF EXISTS trg_pets_racas_atualizado_em ON pets_racas;
CREATE TRIGGER trg_pets_racas_atualizado_em BEFORE UPDATE ON pets_racas FOR EACH ROW EXECUTE FUNCTION fn_definir_atualizado_em();
DROP TRIGGER IF EXISTS trg_pets_portes_atualizado_em ON pets_portes;
CREATE TRIGGER trg_pets_portes_atualizado_em BEFORE UPDATE ON pets_portes FOR EACH ROW EXECUTE FUNCTION fn_definir_atualizado_em();

INSERT INTO sistema_schema_versions(version,description,checksum_sha256)VALUES('app-008-pet-classification-catalogs','Catálogos de espécie, raça e porte dos pets',NULL)ON CONFLICT(version)DO NOTHING;
COMMIT;
