BEGIN;
SET search_path TO pinepet,public;

CREATE TABLE IF NOT EXISTS clientes_sexos(
 id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 codigo varchar(30) NOT NULL UNIQUE,nome varchar(60) NOT NULL UNIQUE,ordem smallint NOT NULL DEFAULT 0,ativo boolean NOT NULL DEFAULT TRUE,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK(codigo~'^[A-Z][A-Z0-9_]{1,29}$'),CHECK(ordem>=0)
);

INSERT INTO clientes_sexos(codigo,nome,ordem)VALUES
 ('FEMININO','Feminino',10),('MASCULINO','Masculino',20),('INTERSEXO','Intersexo',30),('NAO_INFORMADO','Não informado',99)
ON CONFLICT(codigo)DO UPDATE SET nome=EXCLUDED.nome,ordem=EXCLUDED.ordem,ativo=TRUE;

ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_nascimento date;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS id_sexo smallint;
DO $$BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='clientes'::regclass AND conname='fk_clientes_sexo')THEN
  ALTER TABLE clientes ADD CONSTRAINT fk_clientes_sexo FOREIGN KEY(id_sexo)REFERENCES clientes_sexos(id)ON UPDATE RESTRICT ON DELETE RESTRICT;
 END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='clientes'::regclass AND conname='ck_clientes_data_nascimento')THEN
  ALTER TABLE clientes ADD CONSTRAINT ck_clientes_data_nascimento CHECK(data_nascimento IS NULL OR data_nascimento>=DATE '1900-01-01')NOT VALID;
 END IF;
END$$;
CREATE INDEX IF NOT EXISTS ix_clientes_sexo ON clientes(id_estabelecimento,id_sexo)WHERE id_sexo IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_clientes_data_nascimento ON clientes(id_estabelecimento,data_nascimento)WHERE data_nascimento IS NOT NULL;

DROP TRIGGER IF EXISTS trg_clientes_sexos_atualizado_em ON clientes_sexos;
CREATE TRIGGER trg_clientes_sexos_atualizado_em BEFORE UPDATE ON clientes_sexos FOR EACH ROW EXECUTE FUNCTION fn_definir_atualizado_em();

INSERT INTO sistema_schema_versions(version,description,checksum_sha256)VALUES('app-009-client-profile-catalogs','Data de nascimento e catálogo de sexo dos clientes',NULL)ON CONFLICT(version)DO NOTHING;
COMMIT;
