<?php
$title=$title??'PinePet';
$authenticated=App\Core\Auth::user();
$workspace=$authenticated&&!empty($authenticated['profile_complete']);
$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH);
$parts=preg_split('/\s+/u',trim((string)($authenticated['name']??'')));
$initials=strtoupper(substr((string)($parts[0]??''),0,1).substr((string)($parts[count($parts)-1]??''),0,1));
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><title><?=e($title)?></title><meta name="theme-color" content="#035519"><link rel="icon" href="<?=e(asset('/assets/images/logo.svg'))?>"><style nonce="<?=e(CSP_NONCE)?>"><?=inline_asset('assets/css/app.css')?><?=inline_asset('assets/css/onboarding.css')?><?=inline_asset('assets/css/onboarding-responsive.css')?><?=inline_asset('assets/css/onboarding-compact.css')?><?=inline_asset('assets/css/import.css')?><?=inline_asset('assets/css/workspace.css')?><?=inline_asset('assets/css/workspace-overrides.css')?><?=inline_asset('assets/css/workspace-final.css')?></style><script nonce="<?=e(CSP_NONCE)?>" src="<?=e(asset('/assets/vendor/sheetjs/xlsx.full.min.js'))?>" defer></script><script nonce="<?=e(CSP_NONCE)?>" src="<?=e(asset('/assets/js/app.js'))?>" defer></script><script nonce="<?=e(CSP_NONCE)?>" src="<?=e(asset('/assets/js/import.js'))?>" defer></script></head>
<body class="<?=$workspace?'workspace-body':($authenticated?'app-body':'auth-body')?>">
<?php if($workspace):?><button class="sidebar-toggle mobile-sidebar-toggle" type="button" data-sidebar-toggle aria-label="Abrir menu" aria-expanded="false">☰</button><div class="workspace-shell"><aside class="sidebar" data-sidebar><button class="sidebar-brand" type="button" data-sidebar-toggle aria-label="Alternar menu"><img src="<?=e(asset('/assets/images/logo.svg'))?>" alt=""><span><b>Pine</b>Pet</span></button><button class="sidebar-toggle" type="button" data-sidebar-toggle aria-label="Alternar menu" aria-expanded="true">‹</button><nav aria-label="Menu principal"><a class="<?=$path==='/dashboard'?'active':''?>" href="/dashboard"><i>⌂</i><span>Dashboard</span></a><?php foreach(['Agenda'=>'▣','Clientes e pets'=>'♧','Atendimentos'=>'◉','Produtos e estoque'=>'▤','Serviços'=>'✦','Financeiro'=>'$','Equipe'=>'♙','Relatórios'=>'▥']as$item=>$icon):?><span class="disabled" aria-disabled="true"><i><?=e($icon)?></i><span><?=e($item)?><small>Em breve</small></span></span><?php endforeach;?><a class="<?=$path==='/configuracoes'?'active':''?>" href="/configuracoes"><i>⚙</i><span>Configurações</span></a></nav><div class="sidebar-user"><b class="user-initials"><?=e($initials)?></b><span><?=e($authenticated['name'])?></span><form method="post" action="/sair"><?=csrf_field()?><button type="submit">Sair</button></form></div></aside><button class="sidebar-backdrop" type="button" data-sidebar-close aria-label="Fechar menu"></button><main class="workspace-main"><?=$content?></main></div><?php else:?><main class="<?=$authenticated?'app-main':''?>"><?=$content?></main><?php endif;?><div class="toast" role="status" aria-live="polite" hidden></div></body></html>
