<?php
declare(strict_types=1);
namespace App\Repositories;

use App\Core\Database;
use PDO;

final class OnboardingRepository
{
    public function __construct(private readonly Database$database){}
    public function state(int$userId,int$businessId):array
    {
        $s=$this->database->pdo()->prepare("INSERT INTO onboarding_processos(id_usuario,id_estabelecimento)VALUES(:user,:business)ON CONFLICT(id_usuario,id_estabelecimento)DO UPDATE SET id_usuario=EXCLUDED.id_usuario RETURNING etapa,dados,concluido_em");$s->execute(['user'=>$userId,'business'=>$businessId]);$row=$s->fetch();$row['dados']=json_decode((string)$row['dados'],true,32,JSON_THROW_ON_ERROR);return$row;
    }
    public function save(int$userId,int$businessId,int$expectedStep,string$key,array$data):void
    {
        $this->database->transaction(function(PDO$pdo)use($userId,$businessId,$expectedStep,$key,$data):void{$s=$pdo->prepare('SELECT etapa,dados FROM onboarding_processos WHERE id_usuario=:user AND id_estabelecimento=:business AND concluido_em IS NULL FOR UPDATE');$s->execute(['user'=>$userId,'business'=>$businessId]);$row=$s->fetch();if(!is_array($row)||(int)$row['etapa']!==$expectedStep)throw new \RuntimeException('Etapa de onboarding desatualizada.');$all=json_decode((string)$row['dados'],true,32,JSON_THROW_ON_ERROR);$all[$key]=$data;$u=$pdo->prepare('UPDATE onboarding_processos SET etapa=:next,dados=CAST(:data AS jsonb) WHERE id_usuario=:user AND id_estabelecimento=:business');$u->execute(['next'=>$expectedStep+1,'data'=>json_encode($all,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),'user'=>$userId,'business'=>$businessId]);});
    }
    public function paymentMethods():array{return$this->database->pdo()->query('SELECT codigo,nome FROM financeiro_metodos_pagamento WHERE ativo=TRUE ORDER BY ordem,id')->fetchAll();}
    public function complete(int$userId,int$businessId):string
    {
        return$this->database->transaction(function(PDO$pdo)use($userId,$businessId):string{
            $s=$pdo->prepare('SELECT etapa,dados FROM onboarding_processos WHERE id_usuario=:user AND id_estabelecimento=:business AND concluido_em IS NULL FOR UPDATE');$s->execute(['user'=>$userId,'business'=>$businessId]);$process=$s->fetch();if(!is_array($process)||(int)$process['etapa']!==6)throw new \RuntimeException('Onboarding incompleto.');$all=json_decode((string)$process['dados'],true,32,JSON_THROW_ON_ERROR);$identity=$all['identidade']??[];$health=$all['vacinas']??[];$fiscal=$all['fiscal']??[];$payments=$all['pagamentos']['metodos']??[];$hours=$all['horarios']??[];if(count($hours)!==7)throw new \RuntimeException('Horarios nao configurados.');
            $u=$pdo->prepare('UPDATE acesso_usuarios SET nome_completo=:name,data_nascimento=:birth,sexo_biologico=:sex,cpf=:cpf,cadastro_completo_em=NOW(),updated_at=NOW(),version_lock=version_lock+1 WHERE id=:user AND id_estabelecimento=:business AND cadastro_completo_em IS NULL AND deleted_at IS NULL');$u->execute(['name'=>$identity['name'],'birth'=>$identity['birth_date'],'sex'=>$identity['sex'],'cpf'=>$identity['cpf'],'user'=>$userId,'business'=>$businessId]);if($u->rowCount()!==1)throw new \RuntimeException('Cadastro ja concluido ou vinculo invalido.');
            $company=$identity['company']??[];$trade=$company['nome_fantasia']??null;$trade=$trade?:($company['razao_social']??$identity['trade_name']);$pdo->prepare('UPDATE organizacao_estabelecimentos SET cnpj=:cnpj,razao_social=:legal,nome_fantasia=:trade,municipio=:city,uf=:uf,updated_at=NOW() WHERE id=:business AND deleted_at IS NULL')->execute(['cnpj'=>$identity['has_cnpj']?$identity['cnpj']:null,'legal'=>$company['razao_social']??null,'trade'=>$trade,'city'=>$company['municipio']??null,'uf'=>$company['uf']??null,'business'=>$businessId]);
            if(!empty($identity['has_cnpj']))$this->saveCompany($pdo,$businessId,$company);
            [$first,$last]=$this->splitName($identity['name']);$p=$pdo->prepare('INSERT INTO equipe_profissionais(id_estabelecimento,nome,sobrenome,cpf,data_nascimento,email,telefone,whatsapp_com_ddd,cargo,especialidade,ativo)SELECT :business,:first,:last,:cpf,:birth,u.email,u.numero_telefone_ddd,u.numero_telefone_ddd,:role,:specialty,TRUE FROM acesso_usuarios u WHERE u.id=:user AND NOT EXISTS(SELECT 1 FROM equipe_profissionais p WHERE p.id_estabelecimento=:business2 AND p.cpf=:cpf2)');$p->execute(['business'=>$businessId,'first'=>$first,'last'=>$last,'cpf'=>$identity['cpf'],'birth'=>$identity['birth_date'],'role'=>$identity['role'],'specialty'=>$identity['specialty']?:null,'user'=>$userId,'business2'=>$businessId,'cpf2'=>$identity['cpf']]);
            $pdo->prepare('INSERT INTO organizacao_configuracoes(id_estabelecimento,aplica_vacinas)VALUES(:business,:vaccines)ON CONFLICT(id_estabelecimento)DO UPDATE SET aplica_vacinas=EXCLUDED.aplica_vacinas')->execute(['business'=>$businessId,'vaccines'=>!empty($health['aplica_vacinas'])?'true':'false']);if(!empty($health['aplica_vacinas']))$pdo->prepare('INSERT INTO saude_responsaveis_tecnicos(id_estabelecimento,nome,cpf,conselho,numero_conselho,uf_conselho,validade_conselho,email,telefone)VALUES(:business,:name,:cpf,:council,:number,:uf,:validity,:email,:phone)ON CONFLICT(id_estabelecimento)DO UPDATE SET nome=EXCLUDED.nome,cpf=EXCLUDED.cpf,conselho=EXCLUDED.conselho,numero_conselho=EXCLUDED.numero_conselho,uf_conselho=EXCLUDED.uf_conselho,validade_conselho=EXCLUDED.validade_conselho,email=EXCLUDED.email,telefone=EXCLUDED.telefone,ativo=TRUE')->execute(['business'=>$businessId,'name'=>$health['rt_name'],'cpf'=>$health['rt_cpf'],'council'=>$health['rt_council'],'number'=>$health['rt_number'],'uf'=>$health['rt_uf'],'validity'=>$health['rt_validity']?:null,'email'=>$health['rt_email']?:null,'phone'=>$health['rt_phone']?:null]);
            $status=!$fiscal['emitir_nf']?'NAO_APLICAVEL':(!empty($fiscal['certificado'])?'ENVIADO':'QUER_CONTRATAR');$pdo->prepare('INSERT INTO fiscal_configuracoes(id_estabelecimento,emitir_nota,status_certificado,oferta_certificado_solicitada)VALUES(:business,:issue,:status,:offer)ON CONFLICT(id_estabelecimento)DO UPDATE SET emitir_nota=EXCLUDED.emitir_nota,status_certificado=EXCLUDED.status_certificado,oferta_certificado_solicitada=EXCLUDED.oferta_certificado_solicitada')->execute(['business'=>$businessId,'issue'=>$fiscal['emitir_nf']?'true':'false','status'=>$status,'offer'=>!empty($fiscal['quer_certificado'])?'true':'false']);
            if(!empty($fiscal['certificado'])){$c=$fiscal['certificado'];$pdo->prepare("UPDATE fiscal_certificados_digitais SET status='REVOGADO',revogado_em=NOW() WHERE id_estabelecimento=:business AND status='ATIVO'")->execute(['business'=>$businessId]);$pdo->prepare('INSERT INTO fiscal_certificados_digitais(id_estabelecimento,nome_original,caminho_cifrado,senha_cifrada,sha256,tamanho_bytes,validade_em)VALUES(:business,:name,:path,:password,:sha,:size,:validity)')->execute(['business'=>$businessId,'name'=>$c['name'],'path'=>$c['path'],'password'=>$c['password'],'sha'=>$c['sha256'],'size'=>$c['size'],'validity'=>$c['valid_until']]);}
            $pdo->prepare('DELETE FROM financeiro_estabelecimentos_metodos WHERE id_estabelecimento=:business')->execute(['business'=>$businessId]);$pay=$pdo->prepare('INSERT INTO financeiro_estabelecimentos_metodos(id_estabelecimento,id_metodo)SELECT :business,id FROM financeiro_metodos_pagamento WHERE codigo=:code AND ativo=TRUE');foreach($payments as$code)$pay->execute(['business'=>$businessId,'code'=>$code]);
            $hour=$pdo->prepare('INSERT INTO organizacao_horarios(id_estabelecimento,dia_semana,fechado,abre_as,fecha_as)VALUES(:business,:day,:closed,:open,:close)ON CONFLICT(id_estabelecimento,dia_semana)DO UPDATE SET fechado=EXCLUDED.fechado,abre_as=EXCLUDED.abre_as,fecha_as=EXCLUDED.fecha_as');foreach($hours as$day=>$h)$hour->execute(['business'=>$businessId,'day'=>(int)$day,'closed'=>$h['closed']?'true':'false','open'=>$h['closed']?null:$h['open'],'close'=>$h['closed']?null:$h['close']]);
            $flow=$pdo->prepare("INSERT INTO atendimento_fluxos(id_estabelecimento,nome,descricao,etapas,ativo)SELECT :business,'Atendimento padrao','Fluxo inicial criado no onboarding','[{\"codigo\":\"CHECKIN\",\"nome\":\"Check-in\",\"ordem\":1},{\"codigo\":\"ATENDIMENTO\",\"nome\":\"Em atendimento\",\"ordem\":2},{\"codigo\":\"FINALIZACAO\",\"nome\":\"Finalizacao\",\"ordem\":3}]'::jsonb,TRUE WHERE NOT EXISTS(SELECT 1 FROM atendimento_fluxos WHERE id_estabelecimento=:business2 AND nome='Atendimento padrao')");$flow->execute(['business'=>$businessId,'business2'=>$businessId]);
            $findFlow=$pdo->prepare("SELECT id FROM atendimento_fluxos WHERE id_estabelecimento=:business AND nome='Atendimento padrao' ORDER BY id LIMIT 1");$findFlow->execute(['business'=>$businessId]);$flowId=$findFlow->fetchColumn();$pdo->prepare('INSERT INTO atendimento_fluxos_preferencias(id_estabelecimento,id_fluxo_padrao)VALUES(:business,:flow)ON CONFLICT(id_estabelecimento)DO UPDATE SET id_fluxo_padrao=EXCLUDED.id_fluxo_padrao')->execute(['business'=>$businessId,'flow'=>$flowId]);
            $pdo->prepare("INSERT INTO sistema_usuarios_permissoes(id_usuario,id_estabelecimento,recurso,acao,permitido)SELECT :user,:business,p.recurso,p.acao,TRUE FROM(VALUES('establishments','read'),('clients','read'),('pets','read'),('schedules','read'),('attendances','read'),('vaccines','read'),('users','read'),('products','read'),('services','read'),('permissions','read'),('codebook','read'),('stock','read'),('stock','write'))p(recurso,acao)ON CONFLICT(id_usuario,id_estabelecimento,recurso,acao)DO NOTHING")->execute(['user'=>$userId,'business'=>$businessId]);
            $pdo->prepare('UPDATE onboarding_processos SET etapa=7,dados=CAST(:data AS jsonb),concluido_em=NOW() WHERE id_usuario=:user AND id_estabelecimento=:business')->execute(['data'=>json_encode($all,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),'user'=>$userId,'business'=>$businessId]);$pdo->prepare("INSERT INTO sistema_autenticacao_eventos(id_usuario,id_estabelecimento,evento,metadata,created_at)VALUES(:user,:business,'primeiro_acesso','{}'::jsonb,NOW())")->execute(['user'=>$userId,'business'=>$businessId]);return(string)$identity['name'];
        });
    }
    private function saveCompany(PDO$pdo,int$businessId,array$c):void{$sql='INSERT INTO organizacao_dados_receita(id_estabelecimento,cnpj,nome_empresarial,nome_fantasia,situacao_cadastral,natureza_juridica,data_abertura,cnae_principal_codigo,cnae_principal_descricao,cep,logradouro,numero,complemento,bairro,municipio,uf,email,telefone,resposta_hash)VALUES(:business,:cnpj,:legal,:trade,:status,:nature,:opened,:cnae,:cnae_desc,:cep,:street,:number,:extra,:district,:city,:uf,:email,:phone,:hash)ON CONFLICT(id_estabelecimento)DO UPDATE SET cnpj=EXCLUDED.cnpj,nome_empresarial=EXCLUDED.nome_empresarial,nome_fantasia=EXCLUDED.nome_fantasia,situacao_cadastral=EXCLUDED.situacao_cadastral,natureza_juridica=EXCLUDED.natureza_juridica,data_abertura=EXCLUDED.data_abertura,cnae_principal_codigo=EXCLUDED.cnae_principal_codigo,cnae_principal_descricao=EXCLUDED.cnae_principal_descricao,cep=EXCLUDED.cep,logradouro=EXCLUDED.logradouro,numero=EXCLUDED.numero,complemento=EXCLUDED.complemento,bairro=EXCLUDED.bairro,municipio=EXCLUDED.municipio,uf=EXCLUDED.uf,email=EXCLUDED.email,telefone=EXCLUDED.telefone,resposta_hash=EXCLUDED.resposta_hash,consultado_em=NOW()';$pdo->prepare($sql)->execute(['business'=>$businessId,'cnpj'=>$c['cnpj'],'legal'=>$c['razao_social'],'trade'=>$c['nome_fantasia'],'status'=>$c['situacao'],'nature'=>$c['natureza_juridica'],'opened'=>$c['data_abertura'],'cnae'=>$c['cnae_codigo'],'cnae_desc'=>$c['cnae_descricao'],'cep'=>$c['cep']?:null,'street'=>$c['logradouro'],'number'=>$c['numero'],'extra'=>$c['complemento'],'district'=>$c['bairro'],'city'=>$c['municipio'],'uf'=>$c['uf'],'email'=>$c['email'],'phone'=>$c['telefone'],'hash'=>$c['resposta_hash']]);}
    private function splitName(string$name):array{$p=preg_split('/\s+/u',trim($name),2);return[(string)$p[0],$p[1]??null];}
}
